# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    container_name: lanterra_db
    image: postgres:12.18
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres_DB}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456ff!}
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: unless-stopped

  pg_admin:
    container_name: pgadmin_lanterra_db
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456ff!}
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    restart: unless-stopped
